/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List service requests
         * @description Returns a paginated, filterable and sortable collection of service requests.
         *     All query parameters are optional and can be combined; unknown parameters
         *     must be ignored by the client and are rejected with `400` by the API.
         */
        get: operations["listServiceRequests"];
        put?: never;
        /**
         * Create a service request
         * @description Creates a new request. The server assigns `id`, `status` (always `OPEN`),
         *     `createdAt`, `updatedAt` and `version` - these must not be sent by the client.
         */
        post: operations["createServiceRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{requestId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique service-request identifier
                 * @example REQ-1001
                 */
                requestId: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        /** Get a service request by ID */
        get: operations["getServiceRequest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{requestId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique service-request identifier
                 * @example REQ-1001
                 */
                requestId: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update the status of a service request
         * @description Moves a request to a new status. The client must echo the `version` it last
         *     read; a mismatch means somebody else changed the record and the API answers
         *     `409`. On success the returned resource carries an incremented `version`.
         *
         *     Allowed transitions:
         *
         *     | From          | To                          |
         *     |---------------|-----------------------------|
         *     | `OPEN`        | `IN_PROGRESS`, `CLOSED`     |
         *     | `IN_PROGRESS` | `RESOLVED`, `OPEN`          |
         *     | `RESOLVED`    | `CLOSED`, `IN_PROGRESS`     |
         *     | `CLOSED`      | *(terminal)*                |
         *
         *     An invalid transition is rejected with `422`.
         */
        patch: operations["updateServiceRequestStatus"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Lifecycle state of a request.
         *
         *     - `OPEN` - logged and awaiting triage
         *     - `IN_PROGRESS` - actively being worked on
         *     - `RESOLVED` - fix applied, awaiting customer confirmation
         *     - `CLOSED` - terminal state, no further changes allowed
         * @example OPEN
         * @enum {string}
         */
        ServiceRequestStatus: "OPEN" | "IN_PROGRESS" | "RESOLVED" | "CLOSED";
        /**
         * @description Business impact of the request, ordered from lowest to highest.
         * @example HIGH
         * @enum {string}
         */
        ServiceRequestPriority: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        /** @description A customer service request as stored by the API. */
        ServiceRequest: {
            /**
             * @description Server-assigned identifier
             * @example REQ-1001
             */
            readonly id: string;
            /**
             * @description Short summary shown in list views
             * @example Unable to access customer portal
             */
            title: string;
            /**
             * @description Full problem statement
             * @example The customer receives "Account locked" after signing in with valid credentials.
             */
            description: string;
            /**
             * @description Free-text classification, e.g. Access, Billing, Network, Outage
             * @example Access
             */
            category: string;
            priority: components["schemas"]["ServiceRequestPriority"];
            /** @description Set to `OPEN` on creation and changed only through the status endpoint. */
            readonly status: components["schemas"]["ServiceRequestStatus"];
            /**
             * @description Name of the person who raised the request
             * @example Example Customer
             */
            requesterName: string;
            /**
             * Format: email
             * @description Contact address for follow-up
             * @example customer@example.com
             */
            requesterEmail: string;
            /**
             * Format: date-time
             * @description Creation timestamp (RFC 3339, UTC)
             * @example 2026-02-10T08:15:00Z
             */
            readonly createdAt: string;
            /**
             * Format: date-time
             * @description Timestamp of the last modification (RFC 3339, UTC)
             * @example 2026-02-11T09:05:30Z
             */
            readonly updatedAt: string;
            /**
             * Format: int32
             * @description Version used for optimistic concurrency control; incremented on every write.
             * @example 4
             */
            readonly version: number;
        };
        /** @description Payload accepted by `POST /requests`. */
        CreateServiceRequest: {
            /** @example Unable to access customer portal */
            title: string;
            /** @example The customer receives "Account locked" after signing in with valid credentials. */
            description: string;
            /** @example Access */
            category: string;
            priority: components["schemas"]["ServiceRequestPriority"];
            /** @example Example Customer */
            requesterName: string;
            /**
             * Format: email
             * @example customer@example.com
             */
            requesterEmail: string;
        };
        /** @description Payload accepted by `PATCH /requests/{requestId}/status`. */
        UpdateServiceRequestStatus: {
            status: components["schemas"]["ServiceRequestStatus"];
            /**
             * Format: int32
             * @description Version of the request as last read by the client
             * @example 3
             */
            version: number;
            /**
             * @description Optional comment recorded with the transition
             * @example Password reset and portal access confirmed with the customer.
             */
            note?: string;
        };
        /** @description A single page of service requests. */
        ServiceRequestPage: {
            /** @description Requests contained in the current page; empty when nothing matches. */
            items: components["schemas"]["ServiceRequest"][];
            /**
             * Format: int32
             * @description One-based number of the returned page
             * @example 1
             */
            page: number;
            /**
             * Format: int32
             * @description Maximum number of items per page
             * @example 10
             */
            pageSize: number;
            /**
             * Format: int32
             * @description Total number of records matching the filters
             * @example 42
             */
            total: number;
            /**
             * Format: int32
             * @description Total number of pages; `0` when there are no matches
             * @example 5
             */
            totalPages: number;
        };
        /** @description RFC 7807 problem document returned for every error response. */
        ProblemDetails: {
            /**
             * Format: uri
             * @description Stable URI identifying the problem type
             * @example https://api.example.test/problems/not-found
             */
            type?: string;
            /**
             * @description Short, human-readable summary safe to display in the UI
             * @example Service request not found
             */
            title: string;
            /**
             * Format: int32
             * @description HTTP status code
             * @example 404
             */
            status: number;
            /**
             * @description Explanation specific to this occurrence
             * @example No service request exists with id REQ-9999.
             */
            detail?: string;
            /**
             * Format: uri-reference
             * @description URI of the request that produced the error
             * @example /api/requests/REQ-9999
             */
            instance?: string;
            /**
             * @description Correlation identifier to quote in support tickets
             * @example b2c4de6f8091
             */
            traceId?: string;
        } & {
            [key: string]: unknown;
        };
        /** @description Problem document extended with per-field validation messages. */
        ValidationProblemDetails: components["schemas"]["ProblemDetails"] & {
            /**
             * @description Map of field name to the list of messages for that field
             * @example {
             *       "title": [
             *         "Title must be at least 3 characters long."
             *       ],
             *       "requesterEmail": [
             *         "Enter a valid email address."
             *       ]
             *     }
             */
            errors: {
                [key: string]: string[];
            };
        };
    };
    responses: {
        /** @description The request is malformed or a query parameter is invalid */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.example.test/problems/bad-request",
                 *       "title": "Invalid request",
                 *       "status": 400,
                 *       "detail": "Query parameter 'pageSize' must be between 1 and 100.",
                 *       "instance": "/api/requests",
                 *       "traceId": "1a2b3c4d5e6f"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Authentication is missing, invalid, or expired */
        Unauthorized: {
            headers: {
                /** @description Challenge describing the expected credentials */
                "WWW-Authenticate"?: string;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.example.test/problems/unauthorized",
                 *       "title": "Unauthorized",
                 *       "status": 401,
                 *       "detail": "The access token is missing or has expired. Sign in again.",
                 *       "instance": "/api/requests",
                 *       "traceId": "4f8c2e20dabc"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description The token is valid but lacks the scope required for this operation */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.example.test/problems/forbidden",
                 *       "title": "Forbidden",
                 *       "status": 403,
                 *       "detail": "Scope 'service-requests.write' is required.",
                 *       "instance": "/api/requests",
                 *       "traceId": "7d0e91ab33f5"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.example.test/problems/not-found",
                 *       "title": "Service request not found",
                 *       "status": 404,
                 *       "detail": "No service request exists with id REQ-9999.",
                 *       "instance": "/api/requests/REQ-9999",
                 *       "traceId": "b2c4de6f8091"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description One or more fields failed validation */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.example.test/problems/validation-error",
                 *       "title": "Validation failed",
                 *       "status": 422,
                 *       "detail": "The submitted service request contains invalid fields.",
                 *       "instance": "/api/requests",
                 *       "traceId": "3ef5a7c91d20",
                 *       "errors": {
                 *         "title": [
                 *           "Title must be at least 3 characters long."
                 *         ],
                 *         "requesterEmail": [
                 *           "Enter a valid email address."
                 *         ]
                 *       }
                 *     }
                 */
                "application/problem+json": components["schemas"]["ValidationProblemDetails"];
            };
        };
        /** @description Unexpected server error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.example.test/problems/internal-error",
                 *       "title": "Internal server error",
                 *       "status": 500,
                 *       "detail": "An unexpected error occurred. Try again later.",
                 *       "instance": "/api/requests",
                 *       "traceId": "8fa10c37bb45"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /**
         * @description Unique service-request identifier
         * @example REQ-1001
         */
        RequestId: string;
        /**
         * @description Case-insensitive substring match against title or requester name
         * @example portal
         */
        Search: string;
        /**
         * @description Filter by status. Omit for all statuses.
         * @example OPEN
         */
        Status: components["schemas"]["ServiceRequestStatus"];
        /**
         * @description Filter by priority. Omit for all priorities.
         * @example HIGH
         */
        Priority: components["schemas"]["ServiceRequestPriority"];
        /**
         * @description Sort expression. Prefix a field with a minus sign for descending order,
         *     e.g. `-createdAt` returns the newest requests first.
         * @example -createdAt
         */
        Sort: "createdAt" | "-createdAt" | "updatedAt" | "-updatedAt" | "priority" | "-priority";
        /**
         * @description One-based page number
         * @example 1
         */
        Page: number;
        /**
         * @description Number of records per page
         * @example 10
         */
        PageSize: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listServiceRequests: {
        parameters: {
            query?: {
                /**
                 * @description Case-insensitive substring match against title or requester name
                 * @example portal
                 */
                search?: components["parameters"]["Search"];
                /**
                 * @description Filter by status. Omit for all statuses.
                 * @example OPEN
                 */
                status?: components["parameters"]["Status"];
                /**
                 * @description Filter by priority. Omit for all priorities.
                 * @example HIGH
                 */
                priority?: components["parameters"]["Priority"];
                /**
                 * @description Sort expression. Prefix a field with a minus sign for descending order,
                 *     e.g. `-createdAt` returns the newest requests first.
                 * @example -createdAt
                 */
                sort?: components["parameters"]["Sort"];
                /**
                 * @description One-based page number
                 * @example 1
                 */
                page?: components["parameters"]["Page"];
                /**
                 * @description Number of records per page
                 * @example 10
                 */
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated service-request list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceRequestPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createServiceRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateServiceRequest"];
            };
        };
        responses: {
            /** @description Service request created */
            201: {
                headers: {
                    /** @description URL of the created request */
                    Location: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "REQ-1001",
                     *       "title": "Unable to access customer portal",
                     *       "description": "The customer receives \"Account locked\" after signing in with valid credentials.",
                     *       "category": "Access",
                     *       "priority": "HIGH",
                     *       "status": "OPEN",
                     *       "requesterName": "Example Customer",
                     *       "requesterEmail": "customer@example.com",
                     *       "createdAt": "2026-02-10T08:15:00Z",
                     *       "updatedAt": "2026-02-10T08:15:00Z",
                     *       "version": 1
                     *     }
                     */
                    "application/json": components["schemas"]["ServiceRequest"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getServiceRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique service-request identifier
                 * @example REQ-1001
                 */
                requestId: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service-request details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "REQ-1002",
                     *       "title": "Duplicate invoice on February statement",
                     *       "description": "Invoice INV-88213 appears twice on the February billing statement.",
                     *       "category": "Billing",
                     *       "priority": "MEDIUM",
                     *       "status": "IN_PROGRESS",
                     *       "requesterName": "Second Customer",
                     *       "requesterEmail": "second.customer@example.com",
                     *       "createdAt": "2026-02-09T13:42:11Z",
                     *       "updatedAt": "2026-02-11T09:05:30Z",
                     *       "version": 4
                     *     }
                     */
                    "application/json": components["schemas"]["ServiceRequest"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateServiceRequestStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique service-request identifier
                 * @example REQ-1001
                 */
                requestId: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateServiceRequestStatus"];
            };
        };
        responses: {
            /** @description Status updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "REQ-1002",
                     *       "title": "Duplicate invoice on February statement",
                     *       "description": "Invoice INV-88213 appears twice on the February billing statement.",
                     *       "category": "Billing",
                     *       "priority": "MEDIUM",
                     *       "status": "RESOLVED",
                     *       "requesterName": "Second Customer",
                     *       "requesterEmail": "second.customer@example.com",
                     *       "createdAt": "2026-02-09T13:42:11Z",
                     *       "updatedAt": "2026-02-12T07:20:44Z",
                     *       "version": 5
                     *     }
                     */
                    "application/json": components["schemas"]["ServiceRequest"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description The request was modified by another operation */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://api.example.test/problems/version-conflict",
                     *       "title": "Update conflict",
                     *       "status": 409,
                     *       "detail": "The request was updated by someone else. Refresh and try again.",
                     *       "instance": "/api/requests/REQ-1002/status",
                     *       "traceId": "60bb7a8342ac"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The requested status transition is not allowed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://api.example.test/problems/validation-error",
                     *       "title": "Invalid status transition",
                     *       "status": 422,
                     *       "detail": "A CLOSED request cannot be reopened.",
                     *       "instance": "/api/requests/REQ-1002/status",
                     *       "traceId": "9c1d5f7740b2",
                     *       "errors": {
                     *         "status": [
                     *           "Transition from CLOSED to IN_PROGRESS is not allowed."
                     *         ]
                     *       }
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ValidationProblemDetails"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
}
